#!/bin/sh

fukumen -e "バナナ+バナナ=シナモン"
# 　大宮
# ✕ 大宮
# ------
# 大井町
# 横浜　
# ------
# 浜松町
fukumen -e "大宮*宮=大井町 & 大宮*大=横浜 & 大井町+横浜０=浜松町"
fukumen -e "TWO * TWO = THREE"
fukumen -e "third+third+third+seven=eight"
fukumen -e "FORTY+TEN+TEN=SIXTY"
